application: awebshell
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /sitemap\.xml
  static_files: sitemap.xml
  upload: sitemap\.xml

- url: /opensearch\.xml
  static_files: opensearch.xml
  upload: opensearch\.xml

- url: /stylesheet
  static_dir: stylesheet

- url: /image
  static_dir: image

- url: /
  script: index.app

- url: /parse
  script: index.app

- url: /parse/.*
  script: parse.app

- url: /ls/.*
  script: ls.app
- url: /ls
  script: index.app

- url: /man/.*
  script: man.app

libraries:
- name: webapp2
  version: "2.5.1"
