application: awebshell
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheet
  static_dir: stylesheet

- url: /image
  static_dir: image

- url: /
  script: index.app

- url: /parse
  script: index.app

- url: /parse/.*
  script: parse.app

libraries:
- name: webapp2
  version: "2.5.1"
